USE SOFTLAND;

SELECT * FROM CFSSIS.ORDEN_COMPRA WHERE ORDEN_COMPRA LIKE 'OC-002236';
SELECT * FROM CFSSIS.PROVEEDOR WHERE PROVEEDOR LIKE 'PR00012';

SELECT U_CLIENTE,TOTAL_A_COMPRAR FROM CFSSIS.ORDEN_COMPRA WHERE ORDEN_COMPRA LIKE 'OC-002236';
SELECT PROVEEDOR FROM CFSSIS.PROVEEDOR WHERE PROVEEDOR LIKE 'PR00012';

--CLIENTE ==> cliente, ORDEN , DESCRIPCION, COLONES, DOLARES.
--PROVEEDOR ==> proveedor(PR0012), FACTURA, DESCRIPCION, COLONES, dolares(TOTAL_A_COMPRAR).


SELECT * FROM CFSSIS.FACTURA WHERE RUBRO1 LIKE '3156';
